name: Deploy site files

on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
      - LICENSE

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Server
        uses: AEnterprise/rsync-deploy@v1.0
        env:
          DEPLOY_KEY: ${{ secrets.BLOG_DEPLOY_KEY }}
          ARGS: -avz --delete --exclude='*.pyc'
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
          FOLDER: ./
          SERVER_IP: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USERNAME }}
          SERVER_DESTINATION: /home
      - name: Restart server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.BLOG_DEPLOY_KEY }}
          #
          script: |
            cd /home
            # hugo -D
            # docker build . -t hugo:v1  
            # docker run --rm -it -p 1313:1313 --name hugo -d hugo:v1 server
